-- Asistent nastavení účtování z historie.
--
-- Globální katalog popisuje pouze význam obecných slov. Konkrétní firemní účty
-- zůstávají v posting_rules / expense_classification_rules. Analýza i následné
-- přeúčtování jsou background joby nad existující import_jobs infrastrukturou.

SET NAMES utf8mb4;

ALTER TABLE import_jobs
    MODIFY COLUMN source ENUM(
        'idoklad', 'fakturoid', 'pdf_isdoc_inbox', 'pdf_ai', 'monthly_export',
        'document_zip_import', 'document_zip_export', 'document_folder_import',
        'closing_package', 'file_import', 'document_backfill',
        'accounting_setup_analysis', 'accounting_history_reclassification'
    ) NOT NULL;

ALTER TABLE expense_classification_rules
    ADD COLUMN IF NOT EXISTS application_mode ENUM('suggest','auto') NOT NULL DEFAULT 'auto'
        AFTER recurring_prepaid;

CREATE TABLE IF NOT EXISTS expense_keyword_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_version INT UNSIGNED NOT NULL DEFAULT 1,
    locale CHAR(2) NOT NULL DEFAULT 'cs',
    concept_key VARCHAR(64) NOT NULL,
    phrase VARCHAR(120) NOT NULL,
    polarity ENUM('positive','veto') NOT NULL DEFAULT 'positive',
    confidence DECIMAL(4,3) NOT NULL DEFAULT 0.900,
    expense_kind ENUM('service','material','small_asset','fixed_asset') NULL,
    target_account_code VARCHAR(20) NULL,
    requires_review TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_expense_keyword_catalog (catalog_version, locale, concept_key, phrase, polarity),
    KEY idx_expense_keyword_lookup (catalog_version, locale, is_active, concept_key),
    CONSTRAINT chk_expense_keyword_confidence CHECK (confidence >= 0 AND confidence <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_setup_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    supplier_id INT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    scope_json JSON NOT NULL,
    catalog_version INT UNSIGNED NOT NULL,
    input_hash CHAR(64) NULL,
    chart_hash CHAR(64) NULL,
    rules_hash CHAR(64) NULL,
    summary_json JSON NULL,
    created_by INT UNSIGNED NOT NULL,
    completed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_accounting_setup_job (job_id),
    KEY idx_accounting_setup_supplier (supplier_id, id),
    CONSTRAINT fk_accounting_setup_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT fk_accounting_setup_job FOREIGN KEY (job_id) REFERENCES import_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_setup_proposals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id BIGINT UNSIGNED NOT NULL,
    supplier_id INT UNSIGNED NOT NULL,
    proposal_type ENUM('chart_account','expense_rule','posting_rule','bank_rule','asset_candidate','data_quality') NOT NULL,
    signature CHAR(64) NOT NULL,
    title VARCHAR(190) NOT NULL,
    confidence DECIMAL(4,3) NOT NULL,
    occurrence_count INT UNSIGNED NOT NULL DEFAULT 0,
    affected_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    proposal_json JSON NOT NULL,
    evidence_json JSON NOT NULL,
    decision ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    decided_by INT UNSIGNED NULL,
    decided_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_accounting_setup_proposal (run_id, proposal_type, signature),
    KEY idx_accounting_setup_proposal_list (supplier_id, run_id, proposal_type, decision, confidence),
    CONSTRAINT fk_accounting_setup_proposal_run FOREIGN KEY (run_id) REFERENCES accounting_setup_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_accounting_setup_proposal_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT chk_accounting_setup_confidence CHECK (confidence >= 0 AND confidence <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_setup_rule_bundles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id BIGINT UNSIGNED NOT NULL,
    supplier_id INT UNSIGNED NOT NULL,
    bundle_hash CHAR(64) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    approved_by INT UNSIGNED NOT NULL,
    approved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_accounting_setup_bundle_run (run_id),
    KEY idx_accounting_setup_bundle_supplier (supplier_id, id),
    CONSTRAINT fk_accounting_setup_bundle_run FOREIGN KEY (run_id) REFERENCES accounting_setup_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_accounting_setup_bundle_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accounting_reclassification_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id BIGINT UNSIGNED NOT NULL,
    bundle_id BIGINT UNSIGNED NOT NULL,
    supplier_id INT UNSIGNED NOT NULL,
    purchase_invoice_id BIGINT UNSIGNED NOT NULL,
    status ENUM('pending','unchanged','would_change','applied','skipped','failed') NOT NULL DEFAULT 'pending',
    before_json JSON NULL,
    after_json JSON NULL,
    correction_entry_id BIGINT UNSIGNED NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_accounting_reclass_job_document (job_id, purchase_invoice_id),
    KEY idx_accounting_reclass_bundle (supplier_id, bundle_id, status),
    CONSTRAINT fk_accounting_reclass_job FOREIGN KEY (job_id) REFERENCES import_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_accounting_reclass_bundle FOREIGN KEY (bundle_id) REFERENCES accounting_setup_rule_bundles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_accounting_reclass_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    CONSTRAINT fk_accounting_reclass_purchase FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_accounting_reclass_entry FOREIGN KEY (correction_entry_id) REFERENCES journal_entries(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO expense_keyword_catalog
    (catalog_version, locale, concept_key, phrase, polarity, confidence, expense_kind, target_account_code, requires_review)
VALUES
    (1,'cs','fuel','nafta','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','diesel','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','benzin','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','natural 95','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','natural 98','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','super 95','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','premium diesel','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','premiova nafta','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','adblue','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','ad blue','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','lpg','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','cng','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','phm','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','pohonne hmoty','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','pohonnych hmot','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','palivo','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','efecta','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','verva','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','miles','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','nabijeni vozidla','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','dobijeni elektromobilu','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','nabijeni kwh','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','emobility','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','e-mobility','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','ev charging','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','vehicle recharge','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','motorova nafta','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','automobilovy benzin','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','tankovani phm','positive',0.900,'material',NULL,0),
    (1,'cs','fuel','charging session','positive',0.900,'material',NULL,0),

    (1,'cs','energy','elektrina','positive',0.900,'material','502',0),
    (1,'cs','energy','spotreba elektriny','positive',0.900,'material','502',0),
    (1,'cs','energy','elektricka energie','positive',0.900,'material','502',0),
    (1,'cs','energy','dodavka elektriny','positive',0.900,'material','502',0),
    (1,'cs','energy','spotreba plynu','positive',0.900,'material','502',0),
    (1,'cs','energy','zemni plyn','positive',0.900,'material','502',0),
    (1,'cs','energy','dodavka plynu','positive',0.900,'material','502',0),
    (1,'cs','energy','dodavka tepla','positive',0.900,'material','502',0),
    (1,'cs','energy','tepelna energie','positive',0.900,'material','502',0),
    (1,'cs','energy','vodne a stocne','positive',0.900,'material','502',0),
    (1,'cs','energy','vodne stocne','positive',0.900,'material','502',0),
    (1,'cs','energy','dodavka vody','positive',0.850,'material','502',0),
    (1,'cs','energy','spotreba energie','positive',0.900,'material','502',0),

    (1,'cs','material','dr material','positive',0.900,'material',NULL,0),
    (1,'cs','material','drobny material','positive',0.900,'material',NULL,0),
    (1,'cs','material','kabelaz','positive',0.900,'material',NULL,0),
    (1,'cs','material','toner','positive',0.900,'material',NULL,0),
    (1,'cs','material','cartridge','positive',0.900,'material',NULL,0),
    (1,'cs','material','papir','positive',0.900,'material',NULL,0),
    (1,'cs','material','kancelarske potreby','positive',0.900,'material',NULL,0),
    (1,'cs','material','cistici prostredky','positive',0.850,'material',NULL,0),
    (1,'cs','material','obalovy material','positive',0.850,'material',NULL,0),
    (1,'cs','material','pracovni pomucky','positive',0.800,'material',NULL,1),
    (1,'cs','material','spotrebni material','positive',0.900,'material',NULL,0),
    (1,'cs','material','kancelarsky papir','positive',0.900,'material',NULL,0),
    (1,'cs','material','inkoustova cartridge','positive',0.900,'material',NULL,0),
    (1,'cs','material','obaly','positive',0.800,'material',NULL,1),
    (1,'cs','material','hygienicke potreby','positive',0.850,'material',NULL,0),
    (1,'cs','material','dezinfekce','positive',0.850,'material',NULL,0),
    (1,'cs','material','pracovni rukavice','positive',0.850,'material',NULL,0),
    (1,'cs','material','nahradni dil','positive',0.800,'material',NULL,1),
    (1,'cs','material','spojovaci material','positive',0.850,'material',NULL,0),
    (1,'cs','material','elektroinstalacni material','positive',0.850,'material',NULL,0),
    (1,'cs','material','ochranne sklo','positive',0.700,'material',NULL,1),
    (1,'cs','material','kryt na mobil','positive',0.700,'material',NULL,1),
    (1,'cs','material','kabely','positive',0.700,'material',NULL,1),
    (1,'cs','material','folie','positive',0.700,'material',NULL,1),

    (1,'cs','small_asset','tablet','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','notebook','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','kavovar','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','skartovac','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','flash disk','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','flashdisk','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','monitor','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','dr majetek','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','drobny majetek','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','klavesnice','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','tiskarna','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','router','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','dokovaci stanice','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','webkamera','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','sluchatka','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','reproduktor','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','pevny disk','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','thinkpad','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','macbook','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','ipad','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','ultrabook','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','chromebook','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','powerbank','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','nas server','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','wallbox','positive',0.850,'small_asset',NULL,1),
    (1,'cs','small_asset','pocitac','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','stolni pocitac','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','desktop','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','laptop','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','pracovni stanice','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','server','positive',0.850,'small_asset',NULL,1),
    (1,'cs','small_asset','serverove uloziste','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','diskove pole','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','sitovy prepinac','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','access point','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','wifi router','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','zalozni zdroj','positive',0.850,'small_asset',NULL,1),
    (1,'cs','small_asset','ups','positive',0.850,'small_asset',NULL,1),
    (1,'cs','small_asset','projektor','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','skener','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','kopirka','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','mobilni telefon','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','smartphone','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','fotoaparat','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','kancelarska zidle','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','pracovni stul','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','merici pristroj','positive',0.900,'small_asset',NULL,0),
    (1,'cs','small_asset','telefon','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','mobil','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','mob tel','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','vybaveni','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','kabel','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','kryt','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','dr vydaje','positive',0.600,'small_asset',NULL,1),
    (1,'cs','small_asset','zarizeni','positive',0.600,'small_asset',NULL,1),

    (1,'cs','insurance','pojisteni','positive',0.900,'service','548',0),
    (1,'cs','insurance','pojistne','positive',0.900,'service','548',0),
    (1,'cs','insurance','pojistneho','positive',0.900,'service','548',0),
    (1,'cs','insurance','havarijni pojisteni','positive',0.900,'service','548',0),
    (1,'cs','insurance','povinne ruceni','positive',0.900,'service','548',0),

    (1,'cs','repair','oprava','positive',0.900,'service','511',0),
    (1,'cs','repair','opravy','positive',0.900,'service','511',0),
    (1,'cs','repair','opravu','positive',0.900,'service','511',0),
    (1,'cs','repair','udrzba','positive',0.900,'service','511',0),
    (1,'cs','repair','udrzbu','positive',0.900,'service','511',0),
    (1,'cs','repair','udrzovani','positive',0.900,'service','511',0),
    (1,'cs','repair','servisni prohlidka','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','autoservis','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','pneuservis','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','servis vozu','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','servis vozidla','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','servis vozidel','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','servis auta','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','stk','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','emise','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','pneu','positive',0.900,'service','511',0),
    (1,'cs','vehicle_repair','geometrie','positive',0.900,'service','511',0),

    (1,'cs','service','sluzba','positive',0.750,'service',NULL,1),
    (1,'cs','service','sluzby','positive',0.600,'service',NULL,1),
    (1,'cs','service','ucetni sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','pravni sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','it sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','konzultace','positive',0.850,'service',NULL,0),
    (1,'cs','service','skoleni','positive',0.850,'service',NULL,0),
    (1,'cs','service','hosting','positive',0.900,'service',NULL,0),
    (1,'cs','service','cloud','positive',0.850,'service',NULL,0),
    (1,'cs','service','licence','positive',0.900,'service',NULL,0),
    (1,'cs','service','predplatne','positive',0.900,'service',NULL,0),
    (1,'cs','service','clenstvi','positive',0.850,'service',NULL,0),
    (1,'cs','service','najem','positive',0.900,'service',NULL,0),
    (1,'cs','service','najemne','positive',0.900,'service',NULL,0),
    (1,'cs','service','pronajem','positive',0.900,'service',NULL,0),
    (1,'cs','service','pujcovne','positive',0.900,'service',NULL,0),
    (1,'cs','service','leasing','positive',0.850,'service',NULL,1),
    (1,'cs','service','internet','positive',0.850,'service',NULL,0),
    (1,'cs','service','telefonni tarif','positive',0.900,'service',NULL,0),
    (1,'cs','service','hovorne','positive',0.900,'service',NULL,0),
    (1,'cs','service','reklama','positive',0.850,'service',NULL,0),
    (1,'cs','service','ppc','positive',0.850,'service',NULL,0),
    (1,'cs','service','archivace','positive',0.850,'service',NULL,0),
    (1,'cs','service','doprava','positive',0.850,'service',NULL,0),
    (1,'cs','service','dopravne','positive',0.850,'service',NULL,0),
    (1,'cs','service','postovne','positive',0.850,'service',NULL,0),
    (1,'cs','service','preprava','positive',0.850,'service',NULL,0),
    (1,'cs','service','balne','positive',0.800,'service',NULL,0),
    (1,'cs','service','expedice','positive',0.800,'service',NULL,0),
    (1,'cs','service','montaz','positive',0.850,'service',NULL,0),
    (1,'cs','service','instalace','positive',0.800,'service',NULL,1),
    (1,'cs','service','vyuctovani','positive',0.700,'service',NULL,1),
    (1,'cs','service','pausal','positive',0.750,'service',NULL,1),
    (1,'cs','service','poplatek','positive',0.750,'service',NULL,1),
    (1,'cs','service','danove poradenstvi','positive',0.900,'service',NULL,0),
    (1,'cs','service','audit','positive',0.850,'service',NULL,0),
    (1,'cs','service','technicka podpora','positive',0.850,'service',NULL,0),
    (1,'cs','service','sprava systemu','positive',0.850,'service',NULL,0),
    (1,'cs','service','programatorske prace','positive',0.900,'service',NULL,0),
    (1,'cs','service','vyvoj software','positive',0.900,'service',NULL,0),
    (1,'cs','service','graficke prace','positive',0.900,'service',NULL,0),
    (1,'cs','service','marketingove sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','seo','positive',0.800,'service',NULL,1),
    (1,'cs','service','webhosting','positive',0.900,'service',NULL,0),
    (1,'cs','service','registrace domeny','positive',0.900,'service',NULL,0),
    (1,'cs','service','uklidove sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','ostraha','positive',0.900,'service',NULL,0),
    (1,'cs','service','prekladatelske sluzby','positive',0.900,'service',NULL,0),
    (1,'cs','service','kuryrni sluzba','positive',0.900,'service',NULL,0),
    (1,'cs','service','skladne','positive',0.850,'service',NULL,0),
    (1,'cs','service','provize','positive',0.850,'service',NULL,0),
    (1,'cs','service','zprostredkovani','positive',0.850,'service',NULL,0),

    (1,'cs','personal','optika','positive',0.600,'service',NULL,1),
    (1,'cs','personal','bryle','positive',0.600,'service',NULL,1),
    (1,'cs','personal','bryli','positive',0.600,'service',NULL,1),
    (1,'cs','personal','dioptr','positive',0.600,'service',NULL,1),
    (1,'cs','personal','dioptricke','positive',0.600,'service',NULL,1),
    (1,'cs','personal','chytre hodinky','positive',0.600,'small_asset',NULL,1),
    (1,'cs','personal','smartwatch','positive',0.600,'small_asset',NULL,1),
    (1,'cs','personal','smart watch','positive',0.600,'small_asset',NULL,1),
    (1,'cs','personal','apple watch','positive',0.600,'small_asset',NULL,1),
    (1,'cs','personal','garmin','positive',0.600,'small_asset',NULL,1),
    (1,'cs','personal','fenix','positive',0.600,'small_asset',NULL,1),

    (1,'cs','asset_veto','sluzba','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','doprava','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','dopravne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','postovne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','zaruka','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','doruceni','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','dorucne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','preprava','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','balne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','expedice','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','licence','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','predplatne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','hosting','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','najem','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','najemne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','vyuctovani','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','tarif','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','pausal','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','poplatek','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','servis','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','oprava','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','udrzba','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','pojisteni','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','skoleni','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','konzultace','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','instalace','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','montaz','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','nastaveni','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','nehmotny','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','clenstvi','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','pronajem','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','pujcovne','veto',1.000,NULL,NULL,0),
    (1,'cs','asset_veto','leasing','veto',1.000,NULL,NULL,0),

    (1,'cs','fuel_veto','myti','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','plosna cena','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','poplatek','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','dalnicni','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','mytne','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','znamka','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','parkovani','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','obcerstveni','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','nabijecka','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','charger','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','powerbank','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','power bank','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','adapter','veto',1.000,NULL,NULL,0),
    (1,'cs','fuel_veto','kabel','veto',1.000,NULL,NULL,0),

    (1,'sk','fuel','nafta','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','diesel','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','benzin','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','pohonne hmoty','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','palivo','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','lpg','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','cng','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','adblue','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','tankovanie','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','nabijanie vozidla','positive',0.900,'material',NULL,0),
    (1,'sk','fuel','dobijanie elektromobilu','positive',0.900,'material',NULL,0),
    (1,'sk','energy','elektrina','positive',0.900,'material','502',0),
    (1,'sk','energy','spotreba elektriny','positive',0.900,'material','502',0),
    (1,'sk','energy','elektricka energia','positive',0.900,'material','502',0),
    (1,'sk','energy','dodavka elektriny','positive',0.900,'material','502',0),
    (1,'sk','energy','spotreba plynu','positive',0.900,'material','502',0),
    (1,'sk','energy','zemny plyn','positive',0.900,'material','502',0),
    (1,'sk','energy','dodavka plynu','positive',0.900,'material','502',0),
    (1,'sk','energy','dodavka tepla','positive',0.900,'material','502',0),
    (1,'sk','energy','tepelna energia','positive',0.900,'material','502',0),
    (1,'sk','energy','vodne a stocne','positive',0.900,'material','502',0),
    (1,'sk','energy','dodavka vody','positive',0.850,'material','502',0),
    (1,'sk','energy','spotreba energie','positive',0.900,'material','502',0),
    (1,'sk','material','kancelarske potreby','positive',0.900,'material',NULL,0),
    (1,'sk','material','cistiace prostriedky','positive',0.850,'material',NULL,0),
    (1,'sk','material','spotrebny material','positive',0.900,'material',NULL,0),
    (1,'sk','material','toner','positive',0.900,'material',NULL,0),
    (1,'sk','material','cartridge','positive',0.900,'material',NULL,0),
    (1,'sk','material','papier','positive',0.850,'material',NULL,0),
    (1,'sk','material','obalovy material','positive',0.850,'material',NULL,0),
    (1,'sk','material','hygienicke potreby','positive',0.850,'material',NULL,0),
    (1,'sk','material','kabel','positive',0.700,'material',NULL,1),
    (1,'sk','material','nahradny diel','positive',0.800,'material',NULL,1),
    (1,'sk','small_asset','pocitac','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','tlaciaren','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','drobny majetok','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','notebook','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','laptop','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','tablet','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','monitor','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','router','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','server','positive',0.850,'small_asset',NULL,1),
    (1,'sk','small_asset','skener','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','kavovar','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','mobilny telefon','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','smartfon','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','klavesnica','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','dokovacia stanica','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','sietovy prepinac','positive',0.900,'small_asset',NULL,0),
    (1,'sk','small_asset','zalozny zdroj','positive',0.850,'small_asset',NULL,1),
    (1,'sk','small_asset','projektor','positive',0.900,'small_asset',NULL,0),
    (1,'sk','insurance','poistenie','positive',0.900,'service','548',0),
    (1,'sk','insurance','poistne','positive',0.900,'service','548',0),
    (1,'sk','insurance','pzp','positive',0.900,'service','548',0),
    (1,'sk','insurance','havarijne poistenie','positive',0.900,'service','548',0),
    (1,'sk','repair','oprava','positive',0.900,'service','511',0),
    (1,'sk','repair','udrzba','positive',0.900,'service','511',0),
    (1,'sk','repair','servisna prehliadka','positive',0.900,'service','511',0),
    (1,'sk','vehicle_repair','autoservis','positive',0.900,'service','511',0),
    (1,'sk','vehicle_repair','pneuservis','positive',0.900,'service','511',0),
    (1,'sk','vehicle_repair','servis vozidla','positive',0.900,'service','511',0),
    (1,'sk','vehicle_repair','technicka kontrola','positive',0.900,'service','511',0),
    (1,'sk','vehicle_repair','emisna kontrola','positive',0.900,'service','511',0),
    (1,'sk','service','sluzba','positive',0.600,'service',NULL,1),
    (1,'sk','service','sluzby','positive',0.600,'service',NULL,1),
    (1,'sk','service','uctovne sluzby','positive',0.900,'service',NULL,0),
    (1,'sk','service','pravne sluzby','positive',0.900,'service',NULL,0),
    (1,'sk','service','poradenstvo','positive',0.850,'service',NULL,0),
    (1,'sk','service','konzultacie','positive',0.850,'service',NULL,0),
    (1,'sk','service','skolenie','positive',0.850,'service',NULL,0),
    (1,'sk','service','hosting','positive',0.900,'service',NULL,0),
    (1,'sk','service','internet','positive',0.850,'service',NULL,0),
    (1,'sk','service','reklama','positive',0.850,'service',NULL,0),
    (1,'sk','service','marketing','positive',0.850,'service',NULL,0),
    (1,'sk','service','predplatne','positive',0.900,'service',NULL,0),
    (1,'sk','service','prenajom','positive',0.900,'service',NULL,0),
    (1,'sk','service','postovne','positive',0.850,'service',NULL,0),
    (1,'sk','service','preprava','positive',0.850,'service',NULL,0),
    (1,'sk','service','doprava','positive',0.850,'service',NULL,0),
    (1,'sk','service','montaz','positive',0.850,'service',NULL,0),
    (1,'sk','service','instalacia','positive',0.800,'service',NULL,1),
    (1,'sk','service','technicka podpora','positive',0.850,'service',NULL,0),
    (1,'sk','service','poplatok','positive',0.700,'service',NULL,1),
    (1,'sk','asset_veto','sluzba','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','prenajom','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','doprava','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','postovne','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','predplatne','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','hosting','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','oprava','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','udrzba','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','poistenie','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','skolenie','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','poradenstvo','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','poplatok','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','montaz','veto',1.000,NULL,NULL,0),
    (1,'sk','asset_veto','instalacia','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','parkovanie','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','umyvanie','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','myto','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','dialnicna znamka','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','obcerstvenie','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','poplatok','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','nabijacka','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','nabijaci kabel','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','adapter','veto',1.000,NULL,NULL,0),
    (1,'sk','fuel_veto','wallbox','veto',1.000,NULL,NULL,0),

    (1,'de','fuel','diesel','positive',0.900,'material',NULL,0),
    (1,'de','fuel','benzin','positive',0.900,'material',NULL,0),
    (1,'de','fuel','kraftstoff','positive',0.900,'material',NULL,0),
    (1,'de','fuel','tanken','positive',0.900,'material',NULL,0),
    (1,'de','fuel','super e5','positive',0.900,'material',NULL,0),
    (1,'de','fuel','super e10','positive',0.900,'material',NULL,0),
    (1,'de','fuel','super plus','positive',0.900,'material',NULL,0),
    (1,'de','fuel','autogas','positive',0.900,'material',NULL,0),
    (1,'de','fuel','lpg','positive',0.900,'material',NULL,0),
    (1,'de','fuel','cng','positive',0.900,'material',NULL,0),
    (1,'de','fuel','adblue','positive',0.900,'material',NULL,0),
    (1,'de','fuel','betankung','positive',0.900,'material',NULL,0),
    (1,'de','fuel','ladevorgang','positive',0.900,'material',NULL,0),
    (1,'de','fuel','ladestrom','positive',0.900,'material',NULL,0),
    (1,'de','fuel','e auto laden','positive',0.900,'material',NULL,0),
    (1,'de','energy','stromverbrauch','positive',0.900,'material','502',0),
    (1,'de','energy','elektrische energie','positive',0.900,'material','502',0),
    (1,'de','energy','stromlieferung','positive',0.900,'material','502',0),
    (1,'de','energy','erdgas','positive',0.900,'material','502',0),
    (1,'de','energy','gasverbrauch','positive',0.900,'material','502',0),
    (1,'de','energy','gaslieferung','positive',0.900,'material','502',0),
    (1,'de','energy','fernwarme','positive',0.900,'material','502',0),
    (1,'de','energy','warmeversorgung','positive',0.900,'material','502',0),
    (1,'de','energy','wasser und abwasser','positive',0.900,'material','502',0),
    (1,'de','energy','wasserverbrauch','positive',0.850,'material','502',0),
    (1,'de','energy','energieverbrauch','positive',0.900,'material','502',0),
    (1,'de','material','bueromaterial','positive',0.900,'material',NULL,0),
    (1,'de','material','verbrauchsmaterial','positive',0.900,'material',NULL,0),
    (1,'de','material','toner','positive',0.900,'material',NULL,0),
    (1,'de','material','druckerpatrone','positive',0.900,'material',NULL,0),
    (1,'de','material','papier','positive',0.850,'material',NULL,0),
    (1,'de','material','reinigungsmittel','positive',0.850,'material',NULL,0),
    (1,'de','material','verpackungsmaterial','positive',0.850,'material',NULL,0),
    (1,'de','material','kabel','positive',0.700,'material',NULL,1),
    (1,'de','material','ersatzteil','positive',0.800,'material',NULL,1),
    (1,'de','material','hygieneartikel','positive',0.850,'material',NULL,0),
    (1,'de','small_asset','computer','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','drucker','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','geringwertiges wirtschaftsgut','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','laptop','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','notebook','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','tablet','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','monitor','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','router','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','server','positive',0.850,'small_asset',NULL,1),
    (1,'de','small_asset','scanner','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','kaffeemaschine','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','mobiltelefon','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','smartphone','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','tastatur','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','dockingstation','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','netzwerkswitch','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','projektor','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','buerostuhl','positive',0.900,'small_asset',NULL,0),
    (1,'de','small_asset','usv','positive',0.850,'small_asset',NULL,1),
    (1,'de','insurance','versicherung','positive',0.900,'service','548',0),
    (1,'de','insurance','versicherungsbeitrag','positive',0.900,'service','548',0),
    (1,'de','insurance','kfz versicherung','positive',0.900,'service','548',0),
    (1,'de','insurance','haftpflichtversicherung','positive',0.900,'service','548',0),
    (1,'de','repair','reparatur','positive',0.900,'service','511',0),
    (1,'de','repair','wartung','positive',0.900,'service','511',0),
    (1,'de','repair','instandhaltung','positive',0.900,'service','511',0),
    (1,'de','repair','inspektion','positive',0.900,'service','511',0),
    (1,'de','vehicle_repair','kfz werkstatt','positive',0.900,'service','511',0),
    (1,'de','vehicle_repair','autowerkstatt','positive',0.900,'service','511',0),
    (1,'de','vehicle_repair','reifenservice','positive',0.900,'service','511',0),
    (1,'de','vehicle_repair','fahrzeugservice','positive',0.900,'service','511',0),
    (1,'de','vehicle_repair','hauptuntersuchung','positive',0.900,'service','511',0),
    (1,'de','service','dienstleistung','positive',0.600,'service',NULL,1),
    (1,'de','service','buchhaltung','positive',0.900,'service',NULL,0),
    (1,'de','service','rechtsberatung','positive',0.900,'service',NULL,0),
    (1,'de','service','beratung','positive',0.850,'service',NULL,0),
    (1,'de','service','schulung','positive',0.850,'service',NULL,0),
    (1,'de','service','hosting','positive',0.900,'service',NULL,0),
    (1,'de','service','internet','positive',0.850,'service',NULL,0),
    (1,'de','service','werbung','positive',0.850,'service',NULL,0),
    (1,'de','service','marketing','positive',0.850,'service',NULL,0),
    (1,'de','service','abonnement','positive',0.900,'service',NULL,0),
    (1,'de','service','miete','positive',0.900,'service',NULL,0),
    (1,'de','service','porto','positive',0.850,'service',NULL,0),
    (1,'de','service','lieferung','positive',0.850,'service',NULL,0),
    (1,'de','service','transport','positive',0.850,'service',NULL,0),
    (1,'de','service','versand','positive',0.850,'service',NULL,0),
    (1,'de','service','montage','positive',0.850,'service',NULL,0),
    (1,'de','service','installation','positive',0.800,'service',NULL,1),
    (1,'de','service','technische unterstuetzung','positive',0.850,'service',NULL,0),
    (1,'de','service','gebuehr','positive',0.700,'service',NULL,1),
    (1,'de','asset_veto','dienstleistung','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','miete','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','versand','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','abonnement','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','hosting','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','reparatur','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','wartung','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','versicherung','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','schulung','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','beratung','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','gebuehr','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','montage','veto',1.000,NULL,NULL,0),
    (1,'de','asset_veto','installation','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','parken','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','autowaesche','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','maut','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','vignette','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','verpflegung','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','gebuehr','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','ladegeraet','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','ladekabel','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','adapter','veto',1.000,NULL,NULL,0),
    (1,'de','fuel_veto','wallbox','veto',1.000,NULL,NULL,0),

    (1,'en','fuel','diesel','positive',0.900,'material',NULL,0),
    (1,'en','fuel','petrol','positive',0.900,'material',NULL,0),
    (1,'en','fuel','gasoline','positive',0.900,'material',NULL,0),
    (1,'en','fuel','fuel','positive',0.900,'material',NULL,0),
    (1,'en','fuel','diesel fuel','positive',0.900,'material',NULL,0),
    (1,'en','fuel','motor fuel','positive',0.900,'material',NULL,0),
    (1,'en','fuel','unleaded petrol','positive',0.900,'material',NULL,0),
    (1,'en','fuel','refuelling','positive',0.900,'material',NULL,0),
    (1,'en','fuel','lpg','positive',0.900,'material',NULL,0),
    (1,'en','fuel','cng','positive',0.900,'material',NULL,0),
    (1,'en','fuel','adblue','positive',0.900,'material',NULL,0),
    (1,'en','fuel','ev charging session','positive',0.900,'material',NULL,0),
    (1,'en','fuel','vehicle charging','positive',0.900,'material',NULL,0),
    (1,'en','energy','electricity','positive',0.900,'material','502',0),
    (1,'en','energy','electric energy','positive',0.900,'material','502',0),
    (1,'en','energy','electricity supply','positive',0.900,'material','502',0),
    (1,'en','energy','natural gas','positive',0.900,'material','502',0),
    (1,'en','energy','gas supply','positive',0.900,'material','502',0),
    (1,'en','energy','gas consumption','positive',0.900,'material','502',0),
    (1,'en','energy','district heating','positive',0.900,'material','502',0),
    (1,'en','energy','heat supply','positive',0.900,'material','502',0),
    (1,'en','energy','water and sewerage','positive',0.900,'material','502',0),
    (1,'en','energy','water supply','positive',0.850,'material','502',0),
    (1,'en','energy','utility bill','positive',0.850,'material','502',0),
    (1,'en','energy','energy consumption','positive',0.900,'material','502',0),
    (1,'en','material','office supplies','positive',0.900,'material',NULL,0),
    (1,'en','material','consumables','positive',0.900,'material',NULL,0),
    (1,'en','material','toner','positive',0.900,'material',NULL,0),
    (1,'en','material','ink cartridge','positive',0.900,'material',NULL,0),
    (1,'en','material','printer paper','positive',0.850,'material',NULL,0),
    (1,'en','material','packaging material','positive',0.850,'material',NULL,0),
    (1,'en','material','cleaning supplies','positive',0.850,'material',NULL,0),
    (1,'en','material','cable','positive',0.700,'material',NULL,1),
    (1,'en','material','spare part','positive',0.800,'material',NULL,1),
    (1,'en','material','hygiene supplies','positive',0.850,'material',NULL,0),
    (1,'en','small_asset','computer','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','printer','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','small asset','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','laptop','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','notebook','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','tablet','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','monitor','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','router','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','server','positive',0.850,'small_asset',NULL,1),
    (1,'en','small_asset','scanner','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','coffee machine','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','mobile phone','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','smartphone','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','keyboard','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','docking station','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','network switch','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','projector','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','office chair','positive',0.900,'small_asset',NULL,0),
    (1,'en','small_asset','ups','positive',0.850,'small_asset',NULL,1),
    (1,'en','insurance','insurance','positive',0.900,'service','548',0),
    (1,'en','insurance','insurance premium','positive',0.900,'service','548',0),
    (1,'en','insurance','vehicle insurance','positive',0.900,'service','548',0),
    (1,'en','insurance','liability insurance','positive',0.900,'service','548',0),
    (1,'en','repair','repair','positive',0.900,'service','511',0),
    (1,'en','repair','repairs','positive',0.900,'service','511',0),
    (1,'en','repair','maintenance','positive',0.900,'service','511',0),
    (1,'en','repair','servicing','positive',0.900,'service','511',0),
    (1,'en','vehicle_repair','car service','positive',0.900,'service','511',0),
    (1,'en','vehicle_repair','auto repair','positive',0.900,'service','511',0),
    (1,'en','vehicle_repair','tire service','positive',0.900,'service','511',0),
    (1,'en','vehicle_repair','vehicle service','positive',0.900,'service','511',0),
    (1,'en','vehicle_repair','vehicle inspection','positive',0.900,'service','511',0),
    (1,'en','service','service','positive',0.600,'service',NULL,1),
    (1,'en','service','accounting services','positive',0.900,'service',NULL,0),
    (1,'en','service','legal services','positive',0.900,'service',NULL,0),
    (1,'en','service','consulting','positive',0.850,'service',NULL,0),
    (1,'en','service','training','positive',0.850,'service',NULL,0),
    (1,'en','service','hosting','positive',0.900,'service',NULL,0),
    (1,'en','service','cloud service','positive',0.900,'service',NULL,0),
    (1,'en','service','saas','positive',0.850,'service',NULL,0),
    (1,'en','service','internet service','positive',0.850,'service',NULL,0),
    (1,'en','service','advertising','positive',0.850,'service',NULL,0),
    (1,'en','service','marketing','positive',0.850,'service',NULL,0),
    (1,'en','service','subscription','positive',0.900,'service',NULL,0),
    (1,'en','service','rent','positive',0.900,'service',NULL,0),
    (1,'en','service','postage','positive',0.850,'service',NULL,0),
    (1,'en','service','delivery','positive',0.850,'service',NULL,0),
    (1,'en','service','shipping','positive',0.850,'service',NULL,0),
    (1,'en','service','freight','positive',0.850,'service',NULL,0),
    (1,'en','service','transportation','positive',0.850,'service',NULL,0),
    (1,'en','service','assembly','positive',0.850,'service',NULL,0),
    (1,'en','service','installation','positive',0.800,'service',NULL,1),
    (1,'en','service','technical support','positive',0.850,'service',NULL,0),
    (1,'en','service','audit','positive',0.850,'service',NULL,0),
    (1,'en','service','fee','positive',0.700,'service',NULL,1),
    (1,'en','asset_veto','service','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','rent','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','shipping','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','subscription','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','hosting','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','repair','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','maintenance','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','insurance','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','training','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','consulting','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','fee','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','assembly','veto',1.000,NULL,NULL,0),
    (1,'en','asset_veto','installation','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','parking','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','car wash','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','toll','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','vignette','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','refreshments','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','fee','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','charger','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','charging cable','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','adapter','veto',1.000,NULL,NULL,0),
    (1,'en','fuel_veto','wallbox','veto',1.000,NULL,NULL,0);
