CREATE TABLE IF NOT EXISTS product_assemblies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    supplier_id INT UNSIGNED NOT NULL,
    operation_key VARCHAR(80) COLLATE utf8mb4_bin NOT NULL,
    request_hash CHAR(64) NOT NULL,
    stock_item_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(14,3) NOT NULL,
    status ENUM('posted','reversed') NOT NULL DEFAULT 'posted',
    definition_json LONGTEXT NOT NULL CHECK (JSON_VALID(definition_json)),
    components_json LONGTEXT NOT NULL CHECK (JSON_VALID(components_json)),
    issue_document_id BIGINT UNSIGNED NULL,
    receipt_document_id BIGINT UNSIGNED NULL,
    value_total DECIMAL(16,2) NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reversed_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_product_assembly_operation (supplier_id, operation_key),
    UNIQUE KEY uq_product_assembly_issue (issue_document_id),
    UNIQUE KEY uq_product_assembly_receipt (receipt_document_id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE,
    FOREIGN KEY (stock_item_id) REFERENCES stock_items(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
