<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://schemas.cssz.cz/JMHZ/form/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schemas.cssz.cz/JMHZ/form/1.0" elementFormDefault="qualified"
           version="1.4.3">

  <xs:include schemaLocation="formCommonTypes.xsd"/>

  <xs:element name="cinnostKS" type="cinnostKSType"/>
  <xs:complexType name="cinnostKSType">
    <xs:annotation>
      <xs:documentation>DATOVÝ SCÉNÁŘ V MĚSÍČNÍM HLÁŠENÍ PODLE DRUHU ČINNOSTI:
K,N,O,P,Q,R,S nebo 1 až 9 s příznakem 10502 = pracovní vztah specifické skupiny</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="identifikace" type="identifikaceType"/>
      <xs:element name="souhrnDataZec" type="souhrnDataZecCinnostKSType" minOccurs="0"/>
      <xs:element name="pojisteni" type="pojisteniType"/>
      <xs:element name="vykonavanaPozice" type="vykonavanaPoziceType"/>
      <xs:element name="prijem" type="prijemType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="souhrnDataZecCinnostKSType">
    <xs:sequence>
      <xs:element name="prijmy" type="prijmyCinnostKSType"/>
      <xs:element name="zalohaNaDan" type="zalohaNaDanType" minOccurs="0"/>
      <xs:element name="zvlastniSazbaDane" type="zvlastniSazbaDaneCinnostKSType" minOccurs="0"/>
      <xs:element name="prohlaseniPoplatnika" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Prohlášení poplatníka daně z příjmů ze závislé činnosti
DS: Souhrnná data zaměstnance > Výpočet zálohy na daň (ID 10419)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="prohlaseniPoplatnikaDane" type="prohlaseniPoplatnikaDaneType" minOccurs="0"/>
      <xs:element name="rocniUhrny" type="rocniUhrnyType" minOccurs="0"/>          
      <xs:element name="zdravPojZamestnanec" type="zdravPojZamestnanecType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="prijmyCinnostKSType">
    <xs:complexContent>
      <xs:extension base="prijmyType">
        <xs:sequence>
          <xs:element name="odmenyNerezident" type="cislo8Type" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Zúčtovaný příjem - z toho odměny členů orgánů právnických osob, kteří jsou daňovými nerezidenty ČR
DS: Souhrnná data zaměstnance > Příjem (ID 10416)</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="prispevekZamestnavatele" type="prispevekZamestnavateleType" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="zvlastniSazbaDaneCinnostKSType">
    <xs:complexContent>
      <xs:extension base="zvlastniSazbaDaneType">
        <xs:sequence>
          <xs:element name="odmenaNerezident" type="cislo14Type" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Odměna člena (nerezidenta) orgánu právnické osoby
DS: Souhrnná data zaměstnance > Výpočet daně podle zvláštní sazby daně (ID 10308)</xs:documentation>
             </xs:annotation>
           </xs:element>
           <xs:element name="srazenaDanNerezident" type="cislo14Type" minOccurs="0">
             <xs:annotation>
               <xs:documentation>Sražená záloha na daň z příjmu nerezidenta člena orgánu právnické osoby
DS: Souhrnná data zaměstnance > Výpočet daně podle zvláštní sazby daně (ID 10310)</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>
