<?php

declare(strict_types=1);

namespace MyInvoice\Service\Payroll\Submission\Jmhz;

/**
 * Kam se nález měsíčního hlášení opravuje.
 *
 * Každý kód, který mzdová podání vydávají (výjimka, blokátor, nález
 * připravenosti), tu má druh nápravy, tedy místo v aplikaci, kam UI účetní
 * pošle. Popisek kódu je v `web/src/i18n/{cs,en}.json` pod
 * `payroll.jmhz_gate.codes.<kód>`. Že žádný kód nezůstal bez obojího, hlídá
 * `JmhzCodeCatalogCoverageTest`: dřív UI u padesáti kódů psalo „neznámá
 * blokace" a posílalo na podporu, přestože server věděl, co chybí.
 */
final class JmhzBlockerCatalog
{
    /** @var list<string> */
    public const KINDS = [
        'employment_terms',
        'employment_profile',
        'employment_identity',
        'registration',
        'employee_identity',
        'statutory_evidence',
        'dependants',
        'absences',
        'averages',
        'time',
        'runs',
        'components',
        'ordinary_evidence',
        'employer_annual',
        'office',
        'annual_settlement',
        'takeover',
        'workplace',
        'correction',
        'submission',
        'retry',
        'manual',
        'support',
    ];

    /**
     * Druh nápravy podle kódu, případně s polem, na které se má doskočit.
     *
     * @var array<string,string|array{0:string,1:string}>
     */
    private const REMEDIATION = [
        'eldp_absence_interval_invalid' => 'absences',
        'eldp_absence_kind_unknown' => 'absences',
        'eldp_absence_kind_unsupported' => 'manual',
        'eldp_absence_overlap_unsupported' => 'absences',
        'eldp_absence_source_invalid' => 'absences',
        'eldp_absences_invalid' => 'support',
        'eldp_activity_unsupported' => ['employment_terms', 'activity_code'],
        'eldp_assessment_base_missing' => 'runs',
        'eldp_assessment_base_not_whole_czk' => 'runs',
        'eldp_authority_request_date_invalid' => 'submission',
        'eldp_confirmation_document_corrupt' => 'manual',
        'eldp_confirmation_document_missing' => 'manual',
        'eldp_confirmation_document_required' => 'manual',
        'eldp_confirmation_invalid' => 'submission',
        'eldp_confirmation_note_invalid' => 'submission',
        'eldp_control_submission_state_invalid' => 'manual',
        'eldp_employment_dates_inconsistent' => 'runs',
        'eldp_employment_dates_missing' => 'runs',
        'eldp_employment_not_in_revision' => 'runs',
        'eldp_employment_scope_mismatch' => 'retry',
        'eldp_environment_invalid' => 'support',
        'eldp_excluded_days_exceed_period' => 'absences',
        'eldp_excluded_days_not_confirmed' => 'submission',
        'eldp_excluded_days_sum_mismatch' => 'support',
        'eldp_hash_mismatch' => 'retry',
        'eldp_historic_preparation_available' => 'submission',
        'eldp_idempotency_payload_mismatch' => 'retry',
        'eldp_idempotency_scope_mismatch' => 'retry',
        'eldp_insurance_month_without_income' => 'absences',
        'eldp_jmhz_default_on_demand_exception' => 'submission',
        'eldp_manual_already_fulfilled' => 'manual',
        'eldp_manual_completion_frozen' => 'manual',
        'eldp_manual_date_future' => 'manual',
        'eldp_manual_date_invalid' => 'manual',
        'eldp_manual_reference_invalid' => 'manual',
        'eldp_manual_statement_not_found' => 'manual',
        'eldp_manual_status_invalid' => 'manual',
        'eldp_manual_submitted_frozen' => 'manual',
        'eldp_month_outside_employment' => 'runs',
        'eldp_month_source_ambiguous' => 'runs',
        'eldp_month_source_missing' => 'runs',
        'eldp_no_insurance_period' => 'runs',
        'eldp_no_source_revision' => 'runs',
        'eldp_ppm_childbirth_missing' => 'absences',
        'eldp_ppm_expected_childbirth_missing' => 'absences',
        'eldp_relationship_kind_unsupported' => 'employment_terms',
        'eldp_revision_not_current_approved' => 'runs',
        'eldp_schema_integrity_failed' => 'support',
        'eldp_scope_already_frozen' => 'retry',
        'eldp_social_not_calculated' => 'runs',
        'eldp_social_participation_missing' => 'runs',
        'eldp_social_relationship_ambiguous' => 'runs',
        'eldp_source_hash_mismatch' => 'retry',
        'eldp_source_incomplete' => 'runs',
        'eldp_source_invalid' => 'support',
        'eldp_source_mismatch' => 'retry',
        'eldp_standalone_statement_not_applicable' => 'manual',
        'eldp_submission_replay_mismatch' => 'retry',
        'eldp_submission_replay_state_invalid' => 'retry',
        'eldp_submission_schema_unavailable' => 'support',
        'eldp_takeover_activity_missing' => 'takeover',
        'eldp_takeover_assessment_base_missing' => 'takeover',
        'eldp_takeover_assessment_base_not_whole_czk' => 'takeover',
        'eldp_takeover_employment_dates_ambiguous' => 'takeover',
        'eldp_takeover_employment_dates_inconsistent' => 'takeover',
        'eldp_takeover_employment_end_unknown' => 'takeover',
        'eldp_takeover_employment_unresolved' => 'takeover',
        'eldp_takeover_post_termination_income_unsupported' => 'takeover',
        'eldp_takeover_excluded_days_breakdown_missing' => 'takeover',
        'eldp_takeover_excluded_days_mismatch' => 'takeover',
        'eldp_deducted_days_unknown' => 'manual',
        'eldp_section_15a_history_unavailable' => 'manual',
        'eldp_statement_continues_previous_employment' => 'submission',
        'eldp_prepared_on_future' => 'submission',
        'eldp_excluded_days_exceed_deducted' => 'support',
        'eldp_base_with_fully_excluded_section' => 'absences',
        'eldp_post_termination_small_scale_unsupported' => 'manual',
        'eldp_death_date_invalid' => 'submission',
        'eldp_year_out_of_range' => 'submission',
        'eldp_copy_identity_incomplete' => 'employee_identity',
        'eldp_takeover_insurance_days_exceed_period' => 'takeover',
        'eldp_takeover_insurance_days_missing' => 'takeover',
        'eldp_takeover_month_ambiguous' => 'takeover',
        'eldp_takeover_month_not_substitutable' => 'takeover',
        'eldp_takeover_participation_conflict' => 'takeover',
        'eldp_takeover_relationship_kind_unsupported' => 'takeover',
        'eldp_xml_snapshot_mismatch' => 'retry',
        'eldp_xml_source_invalid' => 'support',
        'eldp_xsd_validation_failed' => 'support',
        // Opravný list a datum vyhotovení se řeší ve formuláři evidenčního listu.
        'eldp_correction_reference_invalid' => 'support',
        'eldp_correction_without_change' => 'submission',
        'eldp_correction_without_original' => 'submission',
        'eldp_post_termination_code_missing' => 'support',
        'eldp_prepared_on_before_period_end' => 'submission',
        'eldp_prepared_on_invalid' => 'submission',
        // Důchodové údaje a lhůta z výzvy se doplňují ve formuláři evidenčního listu.
        'eldp_authority_request_due_on_invalid' => 'submission',
        'eldp_authority_request_due_on_missing' => 'submission',
        'eldp_not_kept_full_old_age_pension' => 'submission',
        'eldp_pension_age_mid_month_unsupported' => 'support',
        'eldp_pension_status_conflict' => 'submission',
        'eldp_pension_status_evidence_mismatch' => 'statutory_evidence',
        'eldp_pension_status_invalid' => 'submission',
        'eldp_pension_status_not_confirmed' => 'submission',
        'jmhz_eldp_section18_days_unresolved' => 'runs',
        'jmhz_original_at_cssz' => 'submission',
        'jmhz_period_submitted_externally' => 'submission',
        'jmhz_submission_late_discount_confirmation_required' => 'submission',
        'jmhz_submission_refreeze_filled_at_missing' => 'support',
        'jmhz_submission_refreeze_guid_not_unique' => 'support',
        'jmhz_submission_refreeze_identity_mismatch' => 'support',
        'jmhz_vrep_response_lost' => 'submission',
        // Riziková práce, dočasné přidělení a odložený příjem (větev concurrency).
        'jmhz_risk_categorization_missing' => ['employment_terms', 'jmhz_risk_categorization_code'],
        'jmhz_temporary_assignment_user_missing' => ['employment_terms', 'jmhz_assignment_user_kind'],
        'jmhz_deferred_income_type_unsupported' => 'manual',
        'jmhz_eldp_deferred_section_invalid' => 'retry',
        'jmhz_xml_deferred_income_period_invalid' => 'support',
        'jmhz_xml_deferred_income_periods_unsupported' => 'manual',
        'jmhz_xml_deferred_income_type_invalid' => 'support',
        'jmhz_xml_risk_categorization_invalid' => ['employment_terms', 'jmhz_risk_categorization_code'],
        'jmhz_xml_temporary_assignment_user_invalid' => ['employment_terms', 'jmhz_assignment_user_kind'],
        'jmhz_acknowledgement_class_mismatch' => 'submission',
        'jmhz_acknowledgement_correlation_missing' => 'submission',
        'jmhz_acknowledgement_endpoint_untrusted' => 'submission',
        'jmhz_acknowledgement_unreadable' => 'submission',
        'jmhz_activity_code' => ['employment_terms', 'activity_code'],
        'jmhz_amendment_without_components' => 'correction',
        'jmhz_amendment_without_regular' => 'correction',
        'jmhz_amount_overflow' => 'support',
        'jmhz_annual_evidence_scope_mismatch' => 'retry',
        'jmhz_annual_evidence_source_missing' => 'annual_settlement',
        'jmhz_annual_request_source_missing' => 'annual_settlement',
        'jmhz_annual_request_status_unresolved' => 'annual_settlement',
        'jmhz_annual_settlement_child_details_unsupported' => 'dependants',
        'jmhz_annual_settlement_performance_source_missing' => 'annual_settlement',
        'jmhz_annual_settlement_request_source_inconsistent' => 'annual_settlement',
        'jmhz_annual_settlement_result_incomplete' => 'annual_settlement',
        'jmhz_annual_settlement_source_inconsistent' => 'annual_settlement',
        'jmhz_apz_instrument_missing' => 'employment_profile',
        'jmhz_attribute_10116_unresolved' => 'ordinary_evidence',
        'jmhz_attribute_10546_unresolved' => 'ordinary_evidence',
        'jmhz_average_hourly_earning_invalid' => 'averages',
        'jmhz_average_hourly_earning_mismatch' => 'averages',
        'jmhz_average_hourly_earning_missing' => 'averages',
        'jmhz_average_hourly_earning_probable_missing' => 'averages',
        'jmhz_average_hourly_earning_unverified' => 'averages',
        'jmhz_cancellation_component_duplicate' => 'correction',
        'jmhz_cancellation_component_invalid' => 'correction',
        'jmhz_cancellation_component_not_frozen' => 'correction',
        'jmhz_cancellation_duplicate_employment' => 'correction',
        'jmhz_cancellation_duplicate_form' => 'correction',
        'jmhz_cancellation_employment_invalid' => 'correction',
        'jmhz_cancellation_guid_mismatch' => 'correction',
        'jmhz_cancellation_has_no_forms' => 'correction',
        'jmhz_cancellation_person_invalid' => 'correction',
        'jmhz_cancellation_target_invalid' => 'correction',
        'jmhz_cancellation_transition_period_forbidden' => 'correction',
        'jmhz_cancellation_window_closed' => 'correction',
        'jmhz_cancellation_would_leave_no_valid_form' => 'correction',
        'jmhz_certificate' => 'submission',
        'jmhz_child_claim_invalid' => 'dependants',
        'jmhz_component_mapping_hash_mismatch' => 'components',
        'jmhz_component_mapping_mismatch' => 'components',
        'jmhz_component_snapshot_hash_mismatch' => 'components',
        'jmhz_content_correction_current_set_invalid' => 'correction',
        'jmhz_content_correction_deadline_expired' => 'correction',
        'jmhz_content_correction_duplicate_employment' => 'correction',
        'jmhz_content_correction_employment_invalid' => 'correction',
        'jmhz_content_correction_envelope_mismatch' => 'correction',
        'jmhz_content_correction_form_guid_changed' => 'correction',
        'jmhz_content_correction_full_set_controls_failed' => 'correction',
        'jmhz_content_correction_new_guid_invalid' => 'correction',
        'jmhz_content_correction_plan_mismatch' => 'correction',
        'jmhz_content_correction_preparation_blocked' => 'retry',
        'jmhz_content_correction_scope_mismatch' => 'correction',
        'jmhz_content_correction_source_form_missing' => 'correction',
        'jmhz_content_correction_source_guid_invalid' => 'correction',
        'jmhz_content_correction_state_invalid' => 'correction',
        'jmhz_content_correction_without_forms' => 'correction',
        'jmhz_control_period_missing' => 'support',
        'jmhz_december_collective_agreement_source_missing' => 'employer_annual',
        'jmhz_december_ownership_form_source_missing' => 'employer_annual',
        'jmhz_december_ozp_annual_source_missing' => 'employer_annual',
        'jmhz_deferral_concurrent_incomplete' => 'runs',
        'jmhz_deferral_conflict' => 'retry',
        'jmhz_deferral_employment_unknown' => 'retry',
        'jmhz_deferral_no_form_left' => 'runs',
        'jmhz_deferral_not_active' => 'retry',
        'jmhz_deferral_not_blocked' => 'retry',
        'jmhz_deferral_regular_frozen' => 'correction',
        'jmhz_deferral_regular_missing' => 'submission',
        'jmhz_deferral_regular_not_accepted' => 'submission',
        'jmhz_deferral_revision_missing' => 'runs',
        'jmhz_deferral_still_blocked' => 'retry',
        'jmhz_delivered_protocol_channel_unsupported' => 'submission',
        'jmhz_delivered_protocol_form_unknown' => 'submission',
        'jmhz_delivered_protocol_kind_unsupported' => 'submission',
        'jmhz_delivered_protocol_period_mismatch' => 'submission',
        'jmhz_delivered_protocol_submission_mismatch' => 'submission',
        'jmhz_delivered_protocol_variable_symbol_mismatch' => 'submission',
        'jmhz_dispatch_attempt_closed' => 'submission',
        'jmhz_dispatch_attempt_unknown' => 'submission',
        'jmhz_dispatch_class_unsupported' => 'submission',
        'jmhz_dispatch_close_premature' => 'submission',
        'jmhz_dispatch_correlation_missing' => 'submission',
        'jmhz_dispatch_payload_missing' => 'submission',
        'jmhz_dispatch_payload_not_frozen' => 'submission',
        'jmhz_dispatch_rejected' => 'submission',
        'jmhz_dispatch_response_unknown' => 'submission',
        'jmhz_dispatch_send_unresolved' => 'submission',
        'jmhz_dispatch_submitted_not_recorded' => 'submission',
        'jmhz_dry_run_is_not_a_submission' => 'submission',
        'jmhz_effective_state_employment_unknown' => 'support',
        'jmhz_effective_state_protocol_conflict' => 'support',
        'jmhz_effective_state_root_invalid' => 'support',
        'jmhz_eldp_absences_unsupported' => 'absences',
        'jmhz_eldp_ppm_childbirth_missing' => 'absences',
        'jmhz_eldp_assessment_base_mismatch' => 'runs',
        'jmhz_eldp_assessment_base_not_whole_czk' => 'runs',
        'jmhz_eldp_capped_base_unsupported' => 'runs',
        'jmhz_eldp_deducted_days_unsupported' => 'manual',
        'jmhz_eldp_base_with_fully_excluded_section' => 'absences',
        'jmhz_eldp_deferred_small_scale_unsupported' => 'runs',
        'jmhz_eldp_code_activity_mismatch' => ['employment_terms', 'activity_code'],
        'jmhz_eldp_confirmation_note_invalid' => 'ordinary_evidence',
        'jmhz_eldp_days_mismatch' => 'absences',
        'jmhz_eldp_deducted_days_unsupported' => 'manual',
        'jmhz_eldp_employment_not_found' => 'runs',
        'jmhz_eldp_employment_scope_mismatch' => 'support',
        'jmhz_eldp_environment_invalid' => 'support',
        'jmhz_eldp_evidence_mismatch' => 'support',
        'jmhz_eldp_evidence_missing' => 'runs',
        'jmhz_eldp_excluded_days_exceed_period' => 'absences',
        'jmhz_eldp_excluded_days_sum_mismatch' => 'absences',
        'jmhz_eldp_excluded_days_unsupported' => 'absences',
        'jmhz_eldp_hash_mismatch' => 'support',
        'jmhz_eldp_idempotency_incomplete' => 'support',
        'jmhz_eldp_idempotency_payload_mismatch' => 'support',
        'jmhz_eldp_idempotency_scope_mismatch' => 'support',
        'jmhz_eldp_import_absence_dates_missing' => 'absences',
        'jmhz_eldp_insurance_month_without_income' => 'absences',
        'jmhz_eldp_interaction_unsupported' => 'ordinary_evidence',
        'jmhz_eldp_interval_invalid' => 'time',
        'jmhz_eldp_interval_outside_employment' => 'time',
        'jmhz_eldp_nonparticipation_section_invalid' => 'runs',
        'jmhz_eldp_ordinary_activity_unsupported' => ['employment_terms', 'activity_code'],
        'jmhz_eldp_period_invalid' => 'time',
        'jmhz_eldp_relation_activity_mismatch' => ['employment_terms', 'activity_code'],
        'jmhz_eldp_relationship_kind_unsupported' => 'employment_terms',
        'jmhz_eldp_revision_not_current_approved' => 'runs',
        'jmhz_eldp_revision_not_found' => 'runs',
        'jmhz_eldp_scenario_unsupported' => 'employment_terms',
        'jmhz_eldp_scope_already_frozen' => 'support',
        'jmhz_eldp_section18_days_exceed_period' => 'absences',
        'jmhz_eldp_section18_days_sum_mismatch' => 'absences',
        'jmhz_eldp_social_not_calculated' => 'runs',
        'jmhz_eldp_social_relationship_mismatch' => 'runs',
        'jmhz_eldp_social_relationship_unsupported' => 'runs',
        'jmhz_eldp_source_hash_mismatch' => 'support',
        'jmhz_eldp_source_invalid' => 'support',
        'jmhz_eldp_source_mismatch' => 'support',
        'jmhz_eldp_work_summary_mismatch' => 'time',
        'jmhz_eldp_work_summary_missing' => 'time',
        'jmhz_employee_social_discount_exclusive' => 'runs',
        'jmhz_employee_social_discount_relationship_unresolved' => 'runs',
        'jmhz_employer_annual_collective_agreement_missing' => 'employer_annual',
        'jmhz_employer_annual_evidence_scope_mismatch' => 'employer_annual',
        'jmhz_employer_annual_ownership_missing' => 'employer_annual',
        'jmhz_employer_annual_ozp_summary_missing' => 'employer_annual',
        'jmhz_employer_part_time_discount_activity_unsupported' => ['employment_terms', 'activity_code'],
        'jmhz_employer_part_time_discount_outcome_missing' => 'employment_terms',
        'jmhz_employer_part_time_discount_reason_missing' => ['employment_terms', 'social_part_time_discount_reason'],
        'jmhz_employer_part_time_discount_unverified' => 'employment_terms',
        'jmhz_employer_part_time_discount_working_time_missing' => ['employment_terms', 'weekly_hours'],
        'jmhz_employer_part_time_discount_working_time_unresolved' => ['employment_terms', 'weekly_hours'],
        'jmhz_employer_rate_category_unverified' => 'employment_terms',
        'jmhz_employment_scope_mismatch' => 'support',
        'jmhz_employment_set_empty' => 'runs',
        'jmhz_employment_without_office' => 'office',
        'jmhz_encryption_certificate_missing' => 'submission',
        'jmhz_encryption_certificate_unreadable' => 'submission',
        'jmhz_encryption_certificate_untrusted' => 'submission',
        'jmhz_encryption_compression_failed' => 'submission',
        'jmhz_encryption_empty_payload' => 'submission',
        'jmhz_encryption_failed' => 'submission',
        'jmhz_encryption_unavailable' => 'submission',
        'jmhz_envelope_filled_at_invalid' => 'submission',
        'jmhz_envelope_form_guid_missing' => 'submission',
        'jmhz_envelope_form_guid_unbound' => 'submission',
        'jmhz_envelope_guid_invalid' => 'submission',
        'jmhz_envelope_guid_not_unique' => 'submission',
        'jmhz_envelope_package_invalid' => 'submission',
        'jmhz_envelope_vendor_invalid' => 'submission',
        'jmhz_excluded_summary_unavailable' => 'correction',
        'jmhz_feature_source' => 'support',
        'jmhz_flag_combination_unsupported' => 'submission',
        'jmhz_form_already_valid' => 'correction',
        'jmhz_form_original_not_valid' => 'correction',
        'jmhz_form_state_unknown' => 'correction',
        'jmhz_form_type_unknown' => 'correction',
        'jmhz_full_submission_unsupported' => 'submission',
        'jmhz_govtalk_class_unknown' => 'submission',
        'jmhz_govtalk_double_signature' => 'submission',
        'jmhz_govtalk_envelope_incomplete' => 'submission',
        'jmhz_govtalk_envelope_type_mismatch' => 'submission',
        'jmhz_govtalk_envelope_type_unknown' => 'submission',
        'jmhz_govtalk_environment_unknown' => 'submission',
        'jmhz_govtalk_payload_invalid' => 'submission',
        'jmhz_govtalk_serialization_failed' => 'submission',
        'jmhz_govtalk_shape_invalid' => 'submission',
        'jmhz_govtalk_shape_unverified' => 'submission',
        'jmhz_govtalk_signature_broke_envelope' => 'submission',
        'jmhz_govtalk_signature_empty' => 'submission',
        'jmhz_govtalk_signer_missing' => 'submission',
        'jmhz_govtalk_variable_symbol_invalid' => 'submission',
        'jmhz_govtalk_variable_symbol_mismatch' => 'submission',
        'jmhz_govtalk_vendor_mismatch' => 'submission',
        'jmhz_identity_employment_scope_mismatch' => 'employment_terms',
        'jmhz_identity_id_ppv_missing' => ['employment_identity', 'jmhz.employment_external_identifier'],
        'jmhz_identity_incomplete' => 'employment_identity',
        'jmhz_identity_missing' => 'employment_identity',
        'jmhz_identity_oic_missing' => ['employment_identity', 'jmhz.person_external_identifier'],
        'jmhz_identity_scope_mismatch' => 'retry',
        'jmhz_identity_unresolved' => 'employment_identity',
        'jmhz_interaction_in13_unresolved' => 'employment_profile',
        'jmhz_interaction_in28_unresolved' => 'employment_profile',
        'jmhz_interaction_in30_unresolved' => 'employment_profile',
        'jmhz_isds_environment_unknown' => 'submission',
        'jmhz_isds_payroll_submission_scope_mismatch' => 'submission',
        'jmhz_isds_protocol_already_processed' => 'submission',
        'jmhz_isds_protocol_ambiguous' => 'submission',
        'jmhz_isds_protocol_attachment_missing' => 'submission',
        'jmhz_isds_protocol_untrusted' => 'submission',
        'jmhz_isds_response_ambiguous' => 'submission',
        'jmhz_isds_response_unmatched' => 'submission',
        'jmhz_mapping_not_allowed' => 'components',
        'jmhz_negative_or_deferred_income_unsupported' => 'components',
        'jmhz_obligation_missing' => 'runs',
        'jmhz_office_variable_symbol_invalid' => 'office',
        'jmhz_office_variable_symbol_mismatch' => 'office',
        'jmhz_office_variable_symbol_missing' => 'office',
        'jmhz_ordinary_evidence_catalog_mismatch' => 'support',
        'jmhz_ordinary_evidence_confirmation_invalid' => 'support',
        'jmhz_ordinary_evidence_deduction_conflict' => 'runs',
        'jmhz_ordinary_evidence_hash_mismatch' => 'retry',
        'jmhz_ordinary_evidence_idempotency_incomplete' => 'retry',
        'jmhz_ordinary_evidence_idempotency_payload_mismatch' => 'retry',
        'jmhz_ordinary_evidence_idempotency_scope_mismatch' => 'retry',
        'jmhz_ordinary_evidence_incomplete' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_interaction_mismatch' => 'retry',
        'jmhz_ordinary_evidence_invalid' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_missing' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_monthly_exception_required' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_not_found' => 'support',
        'jmhz_ordinary_evidence_period_invalid' => 'support',
        'jmhz_ordinary_evidence_positive_unsupported' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_profile_incomplete' => 'runs',
        'jmhz_ordinary_evidence_profile_missing' => 'runs',
        'jmhz_ordinary_evidence_result_mismatch' => 'runs',
        'jmhz_ordinary_evidence_revision_not_current_approved' => 'runs',
        'jmhz_ordinary_evidence_scenario_unsupported' => 'ordinary_evidence',
        'jmhz_ordinary_evidence_scope_already_frozen' => 'retry',
        'jmhz_ordinary_evidence_scope_mismatch' => 'retry',
        'jmhz_ordinary_evidence_selector_mismatch' => 'runs',
        'jmhz_ordinary_evidence_source_hash_mismatch' => 'retry',
        'jmhz_ordinary_evidence_source_invalid' => 'support',
        'jmhz_ordinary_evidence_source_mismatch' => 'retry',
        'jmhz_ordinary_evidence_specification_mismatch' => 'retry',
        'jmhz_ordinary_evidence_values_mismatch' => 'retry',
        'jmhz_period_invalid' => 'support',
        'jmhz_period_mismatch' => 'support',
        'jmhz_person_identifier' => ['employment_identity', 'jmhz.person_external_identifier'],
        'jmhz_person_not_calculated' => 'runs',
        'jmhz_person_set_mismatch' => 'retry',
        'jmhz_preparation_environment_invalid' => 'support',
        'jmhz_preparation_hash_mismatch' => 'retry',
        'jmhz_preparation_idempotency_incomplete' => 'retry',
        'jmhz_preparation_idempotency_scope_mismatch' => 'retry',
        'jmhz_preparation_issue_invalid' => 'support',
        'jmhz_preparation_not_found' => 'support',
        'jmhz_preparation_not_ready' => 'support',
        'jmhz_preparation_source_not_current' => 'retry',
        'jmhz_preparation_too_large' => 'support',
        'jmhz_preparation_version_unsupported' => 'support',
        'jmhz_primary_employment_unresolved' => ['employment_terms', 'is_primary'],
        'jmhz_projection_form_unbound' => 'support',
        'jmhz_projection_path_ambiguous' => 'support',
        'jmhz_projection_path_unknown' => 'support',
        'jmhz_projection_xml_unreadable' => 'support',
        'jmhz_protocol_ambiguous' => 'submission',
        'jmhz_protocol_anchor_unreadable' => 'support',
        'jmhz_protocol_canonicalization_unstable' => 'support',
        'jmhz_protocol_certificate_expired' => 'support',
        'jmhz_protocol_certificate_not_yet_valid' => 'support',
        'jmhz_protocol_chain_broken' => 'support',
        'jmhz_protocol_channel_unsupported' => 'submission',
        'jmhz_protocol_class_mismatch' => 'submission',
        'jmhz_protocol_class_unknown' => 'support',
        'jmhz_protocol_class_unsigned_mismatch' => 'support',
        'jmhz_protocol_correlation_invalid' => 'support',
        'jmhz_protocol_correlation_mismatch' => 'submission',
        'jmhz_protocol_correlation_missing' => 'submission',
        'jmhz_protocol_correlation_unknown' => 'submission',
        'jmhz_protocol_correction_form_unpaired' => 'correction',
        'jmhz_protocol_correction_guid_invalid' => 'correction',
        'jmhz_protocol_digest_algorithm_unknown' => 'support',
        'jmhz_protocol_digest_mismatch' => 'support',
        'jmhz_protocol_employment_identifier_mismatch' => ['employment_identity', 'jmhz.employment_external_identifier'],
        'jmhz_protocol_employment_not_found_at_cssz' => ['employment_identity','jmhz.employment_external_identifier'],
        'jmhz_protocol_environment_unknown' => 'support',
        'jmhz_protocol_error_code_conflict' => 'support',
        'jmhz_protocol_error_code_unknown' => 'support',
        'jmhz_protocol_error_kind_unknown' => 'support',
        'jmhz_protocol_error_message_unreadable' => 'support',
        'jmhz_protocol_error_not_a_control' => 'support',
        'jmhz_protocol_form_mapping_invalid' => 'support',
        'jmhz_protocol_form_outcome_conflict' => 'support',
        'jmhz_protocol_form_unidentified' => 'support',
        'jmhz_protocol_form_unmapped' => 'submission',
        'jmhz_protocol_identifier_unreadable' => 'support',
        'jmhz_protocol_kind_unknown' => 'submission',
        'jmhz_protocol_not_delivered' => 'retry',
        'jmhz_protocol_outcome_conflict' => 'support',
        'jmhz_protocol_package_count_invalid' => 'support',
        'jmhz_protocol_part_unknown' => 'support',
        'jmhz_protocol_period_invalid' => 'support',
        'jmhz_protocol_person_identifier_mismatch' => ['employment_identity', 'jmhz.person_external_identifier'],
        'jmhz_protocol_person_not_found_at_cssz' => ['employment_identity','jmhz.person_external_identifier'],
        'jmhz_protocol_qualifier_conflict' => 'support',
        'jmhz_protocol_qualifier_unknown' => 'support',
        'jmhz_protocol_regular_submission_duplicate' => 'correction',
        'jmhz_protocol_result_not_recorded' => 'submission',
        'jmhz_protocol_result_unknown' => 'support',
        'jmhz_protocol_service_authorization_missing' => 'office',
        'jmhz_protocol_shape_undocumented' => 'submission',
        'jmhz_protocol_reverify_artifact_mismatch' => 'support',
        'jmhz_protocol_reverify_channel_unsupported' => 'submission',
        'jmhz_protocol_reverify_not_found' => 'submission',
        'jmhz_protocol_reverify_unavailable' => 'retry',
        'jmhz_protocol_signature_detached' => 'support',
        'jmhz_protocol_signature_invalid' => 'support',
        'jmhz_protocol_signature_missing' => 'support',
        'jmhz_protocol_signature_scope_unexpected' => 'support',
        'jmhz_protocol_signature_unavailable' => 'support',
        'jmhz_protocol_signature_unreadable' => 'support',
        'jmhz_protocol_signature_verifier_missing' => 'support',
        'jmhz_protocol_signer_missing' => 'support',
        'jmhz_protocol_signer_unreadable' => 'support',
        'jmhz_protocol_signer_untrusted' => 'support',
        'jmhz_protocol_status_conflict' => 'support',
        'jmhz_protocol_status_unknown' => 'support',
        'jmhz_protocol_tax_advance_with_withholding' => 'statutory_evidence',
        'jmhz_protocol_tax_nonresident_with_declaration' => 'registration',
        'jmhz_protocol_tax_reliefs_without_declaration' => 'statutory_evidence',
        'jmhz_protocol_tax_withholding_with_advance' => 'statutory_evidence',
        'jmhz_protocol_tax_withholding_with_declaration' => 'statutory_evidence',
        'jmhz_protocol_tenant_mismatch' => 'submission',
        'jmhz_protocol_tenant_unverifiable' => 'office',
        'jmhz_protocol_timestamp_unreadable' => 'support',
        'jmhz_protocol_too_large' => 'submission',
        'jmhz_protocol_unreadable' => 'submission',
        'jmhz_protocol_untrusted' => 'support',
        'jmhz_protocol_variable_symbol_conflict' => 'submission',
        'jmhz_protocol_variable_symbol_invalid' => 'support',
        'jmhz_protocol_variable_symbol_missing' => 'submission',
        'jmhz_pvpoj_rate_category_unsupported' => 'runs',
        'jmhz_pvpoj_source_not_found' => 'runs',
        'jmhz_pvpoj_whole_czk_required' => 'runs',
        'jmhz_pvpoj_xsd_limit_exceeded' => 'manual',
        'jmhz_readiness_check_failed' => 'support',
        'jmhz_registry' => 'office',
        'jmhz_regular_submission_cancelled' => 'submission',
        'jmhz_relationship_not_calculated' => 'runs',
        'jmhz_relationship_set_mismatch' => 'retry',
        'jmhz_result_employment_set_mismatch' => 'retry',
        'jmhz_result_person_set_mismatch' => 'retry',
        'jmhz_revision_input_mismatch' => 'retry',
        'jmhz_revision_not_current_approved' => 'runs',
        'jmhz_revision_not_found' => 'runs',
        'jmhz_revision_result_mismatch' => 'retry',
        'jmhz_ruleset_mismatch' => 'retry',
        'jmhz_scenario1_advance_tax_incomplete' => 'runs',
        'jmhz_scenario1_advance_tax_missing' => 'runs',
        'jmhz_scenario1_annual_fields_unsupported' => 'annual_settlement',
        'jmhz_scenario1_child_credit_caregiver_identity_missing' => 'dependants',
        'jmhz_scenario1_child_credit_caregiver_inconsistent' => 'dependants',
        'jmhz_scenario1_child_credit_caregiver_unknown' => 'dependants',
        'jmhz_scenario1_child_credit_source_inconsistent' => 'dependants',
        'jmhz_scenario1_child_credit_without_declaration' => 'dependants',
        'jmhz_scenario1_child_identity_incomplete' => 'dependants',
        'jmhz_scenario1_child_order_unsupported' => 'dependants',
        'jmhz_scenario1_concurrent_participation_unsupported' => 'manual',
        'jmhz_scenario1_deductions_unsupported' => 'manual',
        'jmhz_scenario1_earnings_vector_incomplete' => 'components',
        'jmhz_scenario1_health_result_not_calculated' => 'runs',
        'jmhz_scenario1_income_tax_result_not_calculated' => 'runs',
        'jmhz_scenario1_net_result_not_calculated' => 'runs',
        'jmhz_scenario1_pvpoj_source_mismatch' => 'office',
        'jmhz_scenario1_pvpoj_unavailable' => 'runs',
        'jmhz_scenario1_resolution_blocked' => 'support',
        'jmhz_scenario1_scope_unsupported' => 'manual',
        'jmhz_scenario1_social_result_not_calculated' => 'runs',
        'jmhz_scenario1_source_version_unsupported' => 'retry',
        'jmhz_scenario1_statutory_result_not_calculated' => 'runs',
        'jmhz_scenario1_tax_credit_breakdown_unavailable' => 'runs',
        'jmhz_scenario1_whole_czk_required' => 'runs',
        'jmhz_scenario1_withholding_base_missing' => 'runs',
        'jmhz_scenario1_withholding_above_thresholds' => ['employment_terms', 'activity_code'],
        'jmhz_scenario1_withholding_tax_unsupported' => 'manual',
        'jmhz_scenario2_evidence_gap' => 'manual',
        'jmhz_scenario2_frozen_resolution_invalid' => 'retry',
        'jmhz_scenario2_frozen_resolution_missing' => 'retry',
        'jmhz_scenario2_resolution_blocked' => 'support',
        'jmhz_scenario2_scope_unsupported' => 'retry',
        'jmhz_scenario2_source_version_unsupported' => 'retry',
        // Formuláře scénářů 2, 7 a specifické skupiny scénáře 3 aplikace
        // nevydává; hlášení se podává ručně.
        'jmhz_scenario_2_preparation_unsupported' => 'manual',
        'jmhz_scenario_3_preparation_unsupported' => 'manual',
        'jmhz_scenario_7_preparation_unsupported' => 'manual',
        'jmhz_scenario_8_activity_10_forbidden' => ['employment_terms', 'activity_code'],
        'jmhz_scenario_activity_code_invalid' => ['employment_terms', 'activity_code'],
        'jmhz_scenario_activity_code_missing' => ['employment_terms', 'activity_code'],
        'jmhz_scenario_manual_selection_invalid' => 'support',
        'jmhz_scenario_not_supported' => 'employment_terms',
        'jmhz_scenario_profile_unsupported' => 'employment_terms',
        'jmhz_scenario_relationship_detail_invalid' => 'employment_terms',
        'jmhz_scenario_social_insurance_unreportable' => ['employment_terms', 'activity_code'],
        'jmhz_scenario_relationship_detail_missing' => 'employment_terms',
        'jmhz_scenario_relationship_detail_not_applicable' => 'employment_terms',
        'jmhz_schema_integrity_failed' => 'support',
        'jmhz_signing_certificate_expired' => 'submission',
        'jmhz_signing_certificate_not_registered' => 'submission',
        'jmhz_signing_certificate_not_yet_valid' => 'submission',
        'jmhz_signing_certificate_unidentified' => 'submission',
        'jmhz_signing_credential_unlock_failed' => 'submission',
        'jmhz_signing_empty_payload' => 'support',
        'jmhz_signing_failed' => 'support',
        'jmhz_signing_private_key_missing' => 'submission',
        'jmhz_signing_profile_missing' => 'submission',
        'jmhz_signing_serial_unreadable' => 'submission',
        'jmhz_signing_unavailable' => 'support',
        'jmhz_snapshot_hash_mismatch' => 'retry',
        'jmhz_snapshot_invalid' => 'retry',
        'jmhz_snapshot_missing' => 'retry',
        'jmhz_social_multiple_offices' => 'office',
        'jmhz_social_office_allocation_failed' => 'support',
        'jmhz_social_office_unknown' => 'office',
        'jmhz_social_relationship_mismatch' => 'runs',
        'jmhz_social_result_not_calculated' => 'runs',
        'jmhz_social_totals_mismatch' => 'runs',
        'jmhz_software_identification_invalid' => 'support',
        'jmhz_source_invalid' => 'retry',
        'jmhz_source_scope_mismatch' => 'retry',
        'jmhz_special_scenarios_evidence_gap' => 'manual',
        'jmhz_special_scenarios_frozen_resolution_invalid' => 'manual',
        'jmhz_special_scenarios_frozen_resolution_missing' => 'manual',
        'jmhz_special_scenarios_resolution_blocked' => 'support',
        'jmhz_special_scenarios_source_version_unsupported' => 'retry',
        'jmhz_submission_artifact_mismatch' => 'retry',
        'jmhz_submission_component_identity_missing' => 'retry',
        'jmhz_submission_components_missing' => 'correction',
        'jmhz_submission_components_unreadable' => 'retry',
        'jmhz_registration_change_settling' => 'retry',
        'jmhz_submission_controls_failed' => 'submission',
        'jmhz_submission_form_type_invalid' => 'retry',
        'jmhz_submission_frozen_identity_invalid' => 'retry',
        'jmhz_submission_frozen_identity_missing' => 'retry',
        'jmhz_submission_frozen_payload_invalid' => 'retry',
        'jmhz_submission_frozen_payload_missing' => 'retry',
        'jmhz_submission_frozen_period_invalid' => 'retry',
        'jmhz_submission_frozen_xml_unreadable' => 'retry',
        'jmhz_submission_identity_missing' => 'retry',
        'jmhz_submission_obligation_required' => 'correction',
        'jmhz_submission_obligation_scope_mismatch' => 'correction',
        'jmhz_submission_period_missing' => 'retry',
        'jmhz_submission_preparation_blocked' => 'submission',
        'jmhz_submission_replay_mismatch' => 'correction',
        'jmhz_submission_replay_state_invalid' => 'submission',
        'jmhz_submission_run_missing' => 'retry',
        'jmhz_submission_snapshot_hash_missing' => 'retry',
        'jmhz_submission_split_payload' => 'support',
        'jmhz_submission_split_refreeze_unsupported' => 'submission',
        'jmhz_submission_state_unknown' => 'support',
        'jmhz_submission_type_invalid' => 'retry',
        'jmhz_submission_type_unknown' => 'support',
        'jmhz_taxpayer_declaration_unresolved' => 'statutory_evidence',
        'jmhz_verified_boolean_missing' => 'employment_profile',
        'jmhz_vrep_correlation_invalid' => 'support',
        'jmhz_vrep_endpoint_missing' => 'support',
        'jmhz_vrep_http_error' => 'submission',
        'jmhz_vrep_invalid_response' => 'submission',
        'jmhz_vrep_poll_request_mismatch' => 'support',
        'jmhz_vrep_request_empty' => 'support',
        'jmhz_vrep_unavailable' => 'submission',
        'jmhz_work_month_not_approved' => 'time',
        'jmhz_work_summary_v2_missing' => 'time',
        'jmhz_workplace_codebooks_unverified' => 'workplace',
        'jmhz_xml_attribute_unresolved' => 'retry',
        'jmhz_xml_bonus_without_declaration' => 'statutory_evidence',
        'jmhz_xml_child_credit_without_children' => 'dependants',
        'jmhz_xml_credit_without_declaration' => 'statutory_evidence',
        'jmhz_xml_document_version_unsupported' => 'retry',
        'jmhz_xml_eldp_code_required' => 'retry',
        'jmhz_xml_eldp_excluded_days_sum_mismatch' => 'absences',
        'jmhz_xml_eldp_excluded_days_without_code' => 'absences',
        'jmhz_xml_eldp_missing' => 'retry',
        'jmhz_xml_eldp_section18_days_sum_mismatch' => 'absences',
        'jmhz_xml_employee_social_discount_misplaced' => 'statutory_evidence',
        'jmhz_xml_employee_social_discount_zero' => 'statutory_evidence',
        'jmhz_xml_employer_rate_category_unknown' => 'office',
        'jmhz_xml_exempt_income_exceeds_total' => 'runs',
        'jmhz_xml_form_limit_exceeded' => 'correction',
        'jmhz_xml_identity_name_incomplete' => 'employee_identity',
        // Údaj, který zúžený formulář scénáře 6 nevede: podává se ručně.
        'jmhz_xml_international_hire_attribute_unsupported' => 'manual',
        'jmhz_xml_no_valid_form' => 'submission',
        'jmhz_xml_not_byte_stable' => 'support',
        'jmhz_xml_overtime_exceeds_worked_hours' => 'time',
        'jmhz_xml_paid_unworked_hours_below_sickness' => 'absences',
        'jmhz_xml_period_invalid' => 'submission',
        'jmhz_xml_primary_employment_invalid' => ['employment_terms', 'is_primary'],
        'jmhz_xml_prisoner_excluded_days_unsupported' => 'manual',
        'jmhz_xml_pvpoj_missing' => 'runs',
        'jmhz_xml_resolution_blocked' => 'submission',
        'jmhz_xml_scenario_3_profile_unsupported' => 'manual',
        'jmhz_xml_scenario_unsupported' => 'manual',
        'jmhz_xml_serialization_failed' => 'support',
        'jmhz_xml_split_submission_unsupported' => 'support',
        'jmhz_xml_submission_type_unsupported' => 'submission',
        'jmhz_xml_surcharge_total_missing' => 'runs',
        'jmhz_xml_variable_symbol_invalid' => 'office',
        'jmhz_xml_wage_breakdown_without_wage' => 'runs',
        'jmhz_xml_work_summary_missing' => 'time',
        'jmhz_xsd_validation_failed' => 'support',
        'jmhz_zero_report_attribute_unknown' => 'support',
        'jmhz_zero_report_situation_unknown' => 'support',
    ];

    /** @return array{kind:string,field:?string} */
    public static function remediation(string $code, string $entityType = ''): array
    {
        $entry = self::REMEDIATION[$code] ?? null;
        if (is_array($entry)) {
            return ['kind' => $entry[0], 'field' => $entry[1]];
        }
        if (is_string($entry)) {
            return ['kind' => $entry, 'field' => null];
        }

        return ['kind' => self::fallbackKind($entityType), 'field' => null];
    }

    public static function knows(string $code): bool
    {
        return isset(self::REMEDIATION[$code]);
    }

    /** @return list<string> */
    public static function codes(): array
    {
        return array_keys(self::REMEDIATION);
    }

    private static function fallbackKind(string $entityType): string
    {
        return match ($entityType) {
            'employment' => 'employment_terms',
            'person', 'employee' => 'employee_identity',
            'component' => 'components',
            'office' => 'office',
            'run', 'revision' => 'runs',
            default => 'retry',
        };
    }
}
